apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    pull-request:
      owner: PhilippPlotnikov
      repository: aws-local-runtime
      webhook:
        endpoint: /pull-request
        port: "12000"
        method: POST
        url: https://philipp.hybrid-team.cf-cd.com
      events:
        - pull_request
      
      apiToken:
        name: github-token
        key: token
      
      insecure: true
      active: true
      contentType: json
