# 1 Sync PR
# 2 Github workflow
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-pull-request
      eventSourceName: github-event-source
      eventName: pull-request
      filters:
        data:
          - path: body.action
            type: string
            value:
              - "synchronize"     
          - path: body.pull_request.base.ref
            type: string
            value:
              - "main"
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: github-workflow
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: repo
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: repo
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.repo}}"]
          parameters:
            - src:
                dependencyName: github-pull-request
                dataKey: body.pull_request.base.ref
              dest: spec.arguments.parameters.0.value
