apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh.github-create-pr
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: BRANCH
          - name: MESSAGE
          - name: PR_TEMPLATE
          - name: GITHUB_TOKEN_SECRET
      container:
        name: main
        image: quay.io/codefreshplugins/v2-github-create-pr:main
        args:
          - pull-request
          - --base=main
          - --head={{inputs.parameters.BRANCH}}
          - -m={{inputs.parameters.MESSAGE}}
          - --no-edit
          - -m="$(curl ${{PR_TEMPLATE}} )"
        env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: '{{ inputs.parameters.GITHUB_TOKEN_SECRET }}'
                key: token
