apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh.submit-workflow
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: TEMPLATE_NAME
          - name: ENTRYPOINT
          - name: GIT_REPO
          - name: GIT_REVISION
      container:
        name: main
        image: argoproj/argocli
        command:
          - argo
          - submit
          - --from=wftmpl/{{ inputs.parameters.TEMPLATE_NAME }}
          - --entrypoint={{ inputs.parameters.ENTRYPOINT }}
          - -p=GIT_REPO={{ inputs.parameters.GIT_REPO }}
          - -p=GIT_REVISION={{ inputs.parameters.GIT_REVISION }}
          - --watch
