apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh.terminate-workflow
spec:
  templates:
    - name: main
      inputs:
        parameters:
          - name: NAME
            default: ''
          - name: LABEL_SELECTOR
            default: ''
          - name: FIELD_SELECTOR
            default: ''
      container:
        name: main
        image: argoproj/argocli
        command:
          - argo
          - terminate
          - '{{ inputs.parameters.NAME }}'
          - --selector
          - "{{ inputs.parameters.LABEL_SELECTOR }},workflows.argoproj.io/phase=Running"
          - --field-selector
          - "{{ inputs.parameters.FIELD_SELECTOR }}"
